### ISSUE TITLE
Can't get token from /api/auth/token - check for secret fails

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-api#24]
Posting username and password (as secret) to /api/auth/token always fails.
Password is checked to be equal to the 'secret' field in the database. This field always has value of 'supersecret' instead of real password, hence the check fails.

**Comment by subhankarb** [comment]
@Fak3 from command line we are not supposed to use password. If we start using google oauth, then password is not a valid option. That's why we supposed to generate a secret key while the user register and pass that secret key and username while connecting from CLI. 
From UI it is not valid as we can route to google directly.

**Comment by Fak3** [comment]
@subhankarb from the past discussions with @rgrp he insisted to use password in dpm client. But personally I think that we'd better generate eternal tokens or just API-secret-keys, like amazon does, or even use private-public keypairs like github (and heroku?)

**Comment by subhankarb** [comment]
@Fak3  +1 . Let's do it the amazon way.

**Comment by subhankarb** [comment]
Addressed in https://github.com/frictionlessdata/dpr-api/pull/35

**Comment by rgrp** [comment]
@subhankarb how is this addressed in #35? This seems to be something separate related to #9 not #35 afaict ...
