### ISSUE TITLE
[publish] Ingest from BitStore to MetaStore (not API but internal event logic)

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#8]
- [x] May be use lambda to poll data from s3 to RDS ??

**Comment by pwalsh** [comment]
We had some experiment using lambda to poll S3, but it is likely to be buggy, because, *especially* if you are not hashing payloads locally ( cc @Fak3 @rgrp ) and doing the validation work there, you simply never know when the datapackage contents are all present on S3. 

A bad way to "know" would be if uploads are synchronous and then you have some convention to always upload `datapackage.json` last, and then your lambda function could just be polling for the presence of this file, but as I'd said elsewhere I don't recommend doing synchronous uploads.

On OpenSpending ( again, I encourage you all to copy work from there and save time and effort :) ), We use a web hook system (running from [os-conductor](https://github.com/openspending/os-conductor)), and what happens is more or less:

- client pushes to S3 (client in our case one of a python CLI, and a javascript web app)
- client tracks upload status
- when client gets final upload callback (all files are loaded), it hits a webhook, and this web hook starts the S3 -> RDS data pipeline

This combination of a smart client and a simple, event-driven web hooks system is very effective. Definitely Lambda could be used in place of the web hooks.

**Comment by rgrp** [comment]
@pwalsh really good points and syncs with question about whether we need finalize method in #2 /cc @subhankarb

**Comment by rgrp** [comment]
@subhankarb also makes me wonder whether we want to bother with an AWS lambda setup or just do this in webhook (which will run inside of lambda anyway if we are doing zappa ...)

**Comment by subhankarb** [comment]
@rgrp right now the implementation is like a web hook. It is inside the Zappa deployment. When the upload is done S3 push a message in lambda, and one lambda function push the data to RDS.

**Comment by subhankarb** [comment]
@rgrp web hook is better way as it can be far more testable. I already tried the pipeline with s3 event notification. It is working properly but most of the things are out of our control and happening as a black box.

**Comment by rgrp** [comment]
@subhankarb ok - let's go the webhook way!

**Comment by subhankarb** [comment]
@rgrp web hook has been implemented in #41 and was also implemented the s3 notification event capture by #39 .
